### ISSUE TITLE
Exceptions not referencing global namespace 

### ISSUE THREAD

**Issue by awalls** [stilliard/blmreader#1]
Reader.php references the global Exception class but is missing \ before each Exception declaration. Therefore when an exception is thrown it can't find the class to handle it.

**Comment by stilliard** [comment]
Thanks @awalls, 
I'll be able to fix this soon, unless you'd like to submit a pull request for this? :)

**Comment by awalls** [comment]
I did try to submit a pull request but it appears to be locked :)

Adrian.

**Comment by stilliard** [comment]
@awalls , that's odd, do you see a specific error message when trying to fork the code? I can report it to Github later.

**Comment by awalls** [comment]
PR - https://github.com/stilliard/blmreader/pull/2
