### ISSUE TITLE
Error in setup guide

### ISSUE THREAD

**Issue by pipdig** [stilliard/blmreader#5]
There's a missing ";" from the end of the first line of the setup example.  Obviously not a huge issue, but thought I'd mention it. I really just wanted to post here to thank you for sharing the repo! :)

```
$blm = new \BLM\Reader(dirname(__FILE__)  . '/test.blm')
var_dump($blm->toArray());
```

**Comment by stilliard** [comment]
Great catch, thanks @pipdig ! Glad the repo has been useful for you :)
